//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_EventTriggerListenerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.EventTriggerListener), typeof(UnityEngine.EventSystems.EventTrigger));
		L.RegFunction("Get", Get);
		L.RegFunction("OnPointerEnter", OnPointerEnter);
		L.RegFunction("OnPointerExit", OnPointerExit);
		L.RegFunction("OnPointerDown", OnPointerDown);
		L.RegFunction("OnPointerUp", OnPointerUp);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("OnInitializePotentialDrag", OnInitializePotentialDrag);
		L.RegFunction("OnBeginDrag", OnBeginDrag);
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("OnEndDrag", OnEndDrag);
		L.RegFunction("OnDrop", OnDrop);
		L.RegFunction("OnScroll", OnScroll);
		L.RegFunction("OnUpdateSelected", OnUpdateSelected);
		L.RegFunction("OnSelect", OnSelect);
		L.RegFunction("OnDeselect", OnDeselect);
		L.RegFunction("OnMove", OnMove);
		L.RegFunction("OnSubmit", OnSubmit);
		L.RegFunction("OnCancel", OnCancel);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("onPointerEnter", get_onPointerEnter, set_onPointerEnter);
		L.RegVar("onPointerExit", get_onPointerExit, set_onPointerExit);
		L.RegVar("onPointerDown", get_onPointerDown, set_onPointerDown);
		L.RegVar("onPointerUp", get_onPointerUp, set_onPointerUp);
		L.RegVar("onPointerClick", get_onPointerClick, set_onPointerClick);
		L.RegVar("onInitializePotentialDrag", get_onInitializePotentialDrag, set_onInitializePotentialDrag);
		L.RegVar("onBeginDrag", get_onBeginDrag, set_onBeginDrag);
		L.RegVar("onDrag", get_onDrag, set_onDrag);
		L.RegVar("onEndDrag", get_onEndDrag, set_onEndDrag);
		L.RegVar("onDrop", get_onDrop, set_onDrop);
		L.RegVar("onScroll", get_onScroll, set_onScroll);
		L.RegVar("onUpdateSelected", get_onUpdateSelected, set_onUpdateSelected);
		L.RegVar("onSelect", get_onSelect, set_onSelect);
		L.RegVar("onDeselect", get_onDeselect, set_onDeselect);
		L.RegVar("onMove", get_onMove, set_onMove);
		L.RegVar("onSubmit", get_onSubmit, set_onSubmit);
		L.RegVar("onCancel", get_onCancel, set_onCancel);
		L.RegFunction("BaseEventDelegate", LuaFramework_EventTriggerListener_BaseEventDelegate);
		L.RegFunction("AxisEventDelegate", LuaFramework_EventTriggerListener_AxisEventDelegate);
		L.RegFunction("PointerEventDelegate", LuaFramework_EventTriggerListener_PointerEventDelegate);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.GameObject));
			LuaFramework.EventTriggerListener o = LuaFramework.EventTriggerListener.Get(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerEnter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnPointerEnter(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerExit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnPointerExit(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnPointerDown(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnPointerUp(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInitializePotentialDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnInitializePotentialDrag(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBeginDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnBeginDrag(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnDrag(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEndDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnEndDrag(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnDrop(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnScroll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.PointerEventData));
			obj.OnScroll(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdateSelected(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.OnUpdateSelected(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSelect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.OnSelect(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDeselect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.OnDeselect(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.AxisEventData arg0 = (UnityEngine.EventSystems.AxisEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.AxisEventData));
			obj.OnMove(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSubmit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.OnSubmit(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnCancel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.OnCancel(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onPointerEnter(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onPointerEnter"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onPointerExit(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onPointerExit"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onPointerDown(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onPointerDown"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onPointerUp(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onPointerUp"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onPointerClick(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onPointerClick"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onInitializePotentialDrag(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onInitializePotentialDrag"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onBeginDrag(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onBeginDrag"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onDrag(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onDrag"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onEndDrag(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onEndDrag"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onDrop(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onDrop"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onScroll(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onScroll"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onUpdateSelected(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onUpdateSelected"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onSelect(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onSelect"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onDeselect(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onDeselect"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onMove(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onMove"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onSubmit(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onSubmit"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onCancel(IntPtr L)
	{
		ToLua.Push(L, new EventObject("LuaFramework.EventTriggerListener.onCancel"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onPointerEnter(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onPointerEnter' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onPointerEnter += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onPointerEnter");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onPointerEnter -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onPointerExit(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onPointerExit' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onPointerExit += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onPointerExit");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onPointerExit -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onPointerDown(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onPointerDown' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onPointerDown += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onPointerDown");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onPointerDown -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onPointerUp(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onPointerUp' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onPointerUp += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onPointerUp");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onPointerUp -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onPointerClick(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onPointerClick' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onPointerClick += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onPointerClick");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onPointerClick -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onInitializePotentialDrag(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onInitializePotentialDrag' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onInitializePotentialDrag += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onInitializePotentialDrag");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onInitializePotentialDrag -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onBeginDrag(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onBeginDrag' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onBeginDrag += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onBeginDrag");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onBeginDrag -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onDrag(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onDrag' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onDrag += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onDrag");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onDrag -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onEndDrag(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onEndDrag' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onEndDrag += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onEndDrag");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onEndDrag -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onDrop(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onDrop' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onDrop += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onDrop");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onDrop -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onScroll(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onScroll' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), arg0.func);
				obj.onScroll += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.PointerEventDelegate ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onScroll");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.PointerEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onScroll -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onUpdateSelected(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onUpdateSelected' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), arg0.func);
				obj.onUpdateSelected += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onUpdateSelected");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onUpdateSelected -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onSelect(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onSelect' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), arg0.func);
				obj.onSelect += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onSelect");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onSelect -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onDeselect(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onDeselect' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), arg0.func);
				obj.onDeselect += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onDeselect");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onDeselect -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onMove(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onMove' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.AxisEventDelegate ev = (LuaFramework.EventTriggerListener.AxisEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.AxisEventDelegate), arg0.func);
				obj.onMove += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.AxisEventDelegate ev = (LuaFramework.EventTriggerListener.AxisEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onMove");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.AxisEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onMove -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onSubmit(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onSubmit' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), arg0.func);
				obj.onSubmit += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onSubmit");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onSubmit -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onCancel(IntPtr L)
	{
		try
		{
			LuaFramework.EventTriggerListener obj = (LuaFramework.EventTriggerListener)ToLua.CheckObject(L, 1, typeof(LuaFramework.EventTriggerListener));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'LuaFramework.EventTriggerListener.onCancel' can only appear on the left hand side of += or -= when used outside of the type 'LuaFramework.EventTriggerListener'");
			}

			if (arg0.op == EventOp.Add)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), arg0.func);
				obj.onCancel += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				LuaFramework.EventTriggerListener.BaseEventDelegate ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)LuaMisc.GetEventHandler(obj, typeof(LuaFramework.EventTriggerListener), "onCancel");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (LuaFramework.EventTriggerListener.BaseEventDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.onCancel -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaFramework_EventTriggerListener_BaseEventDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.BaseEventDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaFramework_EventTriggerListener_AxisEventDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.AxisEventDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.AxisEventDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaFramework_EventTriggerListener_PointerEventDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(LuaFramework.EventTriggerListener.PointerEventDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

