//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_StringSplitOptionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(System.StringSplitOptions));
		L.RegVar("None", get_None, null);
		L.RegVar("RemoveEmptyEntries", get_RemoveEmptyEntries, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, System.StringSplitOptions.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RemoveEmptyEntries(IntPtr L)
	{
		ToLua.Push(L, System.StringSplitOptions.RemoveEmptyEntries);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		System.StringSplitOptions o = (System.StringSplitOptions)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

